"""
Heartbeat Simulation Mode for the Haptic System.

This module renders a large heart shape on the screen and simulates a human 
heartbeat (a "lub-dub" rhythm) when the user touches the heart. The haptic 
feedback is generated by pulsing the voltage to the maximum limit at specific 
intervals tied to the system clock.
"""

import pygame
import math
from settings import *

class HeartMode:
    """
    Manages the logic and visual representation of the Heartbeat haptic mode.
    
    This class generates a heart polygon using a parametric mathematical equation,
    creates a collision mask to detect touches specifically inside the heart shape,
    and calculates the timing for a two-beat (lub-dub) haptic pulse.
    """
    def __init__(self):
        # Generate the vertices of the heart shape centered on the screen
        self.heart_points = self.create_heart_polygon(WIDTH // 2, HEIGHT // 2, 25)
        
        # Create a temporary transparent surface to draw the heart onto.
        # This is used exclusively to generate an accurate pixel-perfect collision mask.
        temp_surface = pygame.Surface((WIDTH, HEIGHT), pygame.SRCALPHA)
        pygame.draw.polygon(temp_surface, (255, 255, 255), self.heart_points)
        self.mask = pygame.mask.from_surface(temp_surface)
        
        # Initial visual state is "dim" (user is not touching the heart)
        self.visual_color = COLOR_HEART_DIM
        
        # --- Font Definitions ---
        # Initialize fonts for on-screen instructions and thematic text
        self.font_title = pygame.font.SysFont("Arial", 50, bold=True)
        self.font_sub = pygame.font.SysFont("Arial", 30, italic=True)

    def create_heart_polygon(self, center_x, center_y, scale):
        """
        Generates a list of (x, y) coordinates forming a heart shape.
        
        Uses the standard parametric equations for a heart curve:
        x = 16 * sin^3(t)
        y = 13 * cos(t) - 5 * cos(2t) - 2 * cos(3t) - cos(4t)
        
        Args:
            center_x (int): The X coordinate for the center of the heart.
            center_y (int): The Y coordinate for the center of the heart.
            scale (int): Multiplier to increase the physical size of the shape.
            
        Returns:
            list: A list of tuples containing the (x, y) vertex coordinates.
        """
        points = []
        # Iterate from 0 to roughly 2*pi (6.28) mapped to integers
        for t in range(0, 628, 5):
            angle = t / 100.0
            
            # Parametric heart equations
            x = 16 * math.sin(angle) ** 3
            y = 13 * math.cos(angle) - 5 * math.cos(2*angle) - 2 * math.cos(3*angle) - math.cos(4*angle)
            
            # Apply scale and translate to the desired center point.
            # Y is subtracted because Pygame's Y-axis increases downwards.
            px = center_x + (x * scale)
            py = center_y - (y * scale)
            
            points.append((px, py))
            
        return points

    def update(self, finger_pos, current_time):
        """
        Calculates the required haptic signal based on touch and time.
        
        If the user touches inside the heart mask, it uses modulo arithmetic 
        on the current time to create a 1000ms heartbeat cycle featuring a 
        primary beat ("lub") and a secondary beat ("dub").
        
        Args:
            finger_pos (tuple): (x, y) coordinates of the current touch.
            current_time (int): Elapsed time in milliseconds.
            
        Returns:
            tuple: (Waveform type, Frequency, Voltage) to be sent to hardware.
        """
        # Default target values assuming no touch or idle state
        target_freq = CARRIER_FREQ
        target_volt = MIN_VOLTAGE
        self.visual_color = COLOR_HEART_DIM

        if finger_pos:
            try:
                # Check if the touch coordinates fall inside the generated heart mask
                if self.mask.get_at(finger_pos):
                    
                    # Create a looping 1000-millisecond cycle
                    cycle_time = current_time % 1000 
                    
                    # Define the active windows for the two heartbeat pulses
                    is_lub = 0 < cycle_time < 150    # First beat: 0ms to 150ms
                    is_dub = 300 < cycle_time < 450  # Second beat: 300ms to 450ms
                    
                    if is_lub or is_dub:
                        # During a beat, spike the voltage to maximum and brighten the color
                        target_volt = MAX_VOLTAGE # Max Volt (e.g., 4.0V)
                        self.visual_color = COLOR_HEART_BEAT
                    else:
                        # Between beats, return to minimum voltage and a resting color
                        target_volt = MIN_VOLTAGE
                        self.visual_color = COLOR_HEART_SILENT
                        
            except IndexError: 
                # Ignore errors if the finger coordinate goes outside the screen bounds
                pass

        # Always returns a Square wave for this mode to simulate sharp, distinct beats
        return (WAVE_SQUARE, target_freq, target_volt)

    def draw(self, screen, finger_pos):
        """
        Renders the background, the heart polygon, text, and the touch indicator.
        
        Args:
            screen (pygame.Surface): The main display surface.
            finger_pos (tuple/None): The current touch coordinates.
        """
        # Clear the screen to black
        screen.fill(COLOR_BLACK)
        
        # Draw the main heart shape using the calculated color state
        pygame.draw.polygon(screen, self.visual_color, self.heart_points)
        
        # --- TEXT RENDERING ---
        # Main Instruction Title
        text_title = self.font_title.render("Touch the heart to feel the rhythm.", True, COLOR_WHITE)
        rect_title = text_title.get_rect(center=(WIDTH // 2, HEIGHT - 150))
        screen.blit(text_title, rect_title)
        
        # Subtitle (Thematic Quote)
        text_sub = self.font_sub.render("\"Can you feel my heart?\"", True, (200, 200, 200))
        rect_sub = text_sub.get_rect(center=(WIDTH // 2, HEIGHT - 100))
        screen.blit(text_sub, rect_sub)

        # Draw a white circle to visually represent where the user is touching
        if finger_pos:
            pygame.draw.circle(screen, COLOR_WHITE, finger_pos, 20)